name: .NET Desktop CI

on: [push, pull_request, workflow_dispatch]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-2022    # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      solution: ndd2.sln

    steps:
    - uses: actions/checkout@v4

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Build the application
      run: msbuild ${{ env.solution }} /restore /p:Configuration=${{ matrix.configuration }}
